
-- registi
insert into director (id, name, surname, date_of_birth, nationality) values (1, 'Paolo', 'Sorrentino', '1970-05-31', 'Italiana');
insert into director (id, name, surname, date_of_birth, nationality) values (2, 'Matteo', 'Garrone', '1968-10-15', 'Italiana');
insert into director (id, name, surname, date_of_birth, nationality) values (3, 'Alice', 'Rohrwacher', '1981-12-29', 'Italiana');
insert into director (id, name, surname, date_of_birth, nationality) values (4, 'Nanni', 'Moretti', '1953-08-19', 'Italiana');
insert into director (id, name, surname, date_of_birth, nationality) values (5, 'Marco', 'Bellocchio', '1939-11-09', 'Italiana');
insert into director (id, name, surname, date_of_birth, nationality) values (6, 'Greta', 'Gerwig', '1983-08-04', 'Statunitense');
insert into director (id, name, surname, date_of_birth, nationality) values (7, 'Denis', 'Villeneuve', '1967-10-03', 'Canadese');
insert into director (id, name, surname, date_of_birth, nationality) values (8, 'Celine', 'Sciamma', '1978-11-12', 'Francese');
insert into director (id, name, surname, date_of_birth, nationality) values (9, 'Bong', 'Joon-ho', '1969-09-14', 'Sudcoreana');
insert into director (id, name, surname, date_of_birth, nationality) values (10, 'Hirokazu', 'Kore-eda', '1962-06-06', 'Giapponese');
insert into director (id, name, surname, date_of_birth, nationality) values (11, 'Lynne', 'Ramsay', '1969-12-05', 'Britannica');
insert into director (id, name, surname, date_of_birth, nationality) values (12, 'Jacques', 'Audiard', '1952-04-30', 'Francese');
insert into director (id, name, surname, date_of_birth, nationality) values (13, 'Kelly', 'Reichardt', '1964-03-03', 'Statunitense');
insert into director (id, name, surname, date_of_birth, nationality) values (14, 'Cristian', 'Mungiu', '1968-04-27', 'Rumena');
insert into director (id, name, surname, date_of_birth, nationality) values (15, 'Lucrecia', 'Martel', '1966-12-14', 'Argentina');
insert into director (id, name, surname, date_of_birth, nationality) values (16, 'Ruben', 'Ostlund', '1974-04-13', 'Svedese');
insert into director (id, name, surname, date_of_birth, nationality) values (17, 'Agnieszka', 'Holland', '1948-11-28', 'Polacca');
insert into director (id, name, surname, date_of_birth, nationality) values (18, 'Nuri Bilge', 'Ceylan', '1959-01-26', 'Turca');
insert into director (id, name, surname, date_of_birth, nationality) values (19, 'Ari', 'Aster', '1986-07-15', 'Statunitense');
insert into director (id, name, surname, date_of_birth, nationality) values (20, 'Mati', 'Diop', '1982-06-22', 'Francese');

-- film
insert into movie (id, title, year, duration, genre, production_country, director_id) values (1, 'La grande bellezza', 2013, 141, 'Drammatico', 'Italia', 1);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (2, 'E'' stata la mano di Dio', 2021, 130, 'Drammatico', 'Italia', 1);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (3, 'Gomorra', 2008, 137, 'Drammatico', 'Italia', 2);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (4, 'Io Capitano', 2023, 121, 'Drammatico', 'Italia', 2);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (5, 'Lazzaro felice', 2018, 125, 'Drammatico', 'Italia', 3);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (6, 'La chimera', 2023, 130, 'Drammatico', 'Italia', 3);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (7, 'Caro diario', 1993, 100, 'Commedia', 'Italia', 4);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (8, 'La stanza del figlio', 2001, 99, 'Drammatico', 'Italia', 4);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (9, 'Il traditore', 2019, 145, 'Biografico', 'Italia', 5);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (10, 'Rapito', 2023, 134, 'Storico', 'Italia', 5);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (11, 'Lady Bird', 2017, 94, 'Commedia', 'Stati Uniti', 6);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (12, 'Piccole donne', 2019, 135, 'Drammatico', 'Stati Uniti', 6);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (13, 'Arrival', 2016, 116, 'Fantascienza', 'Stati Uniti', 7);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (14, 'Dune', 2021, 155, 'Fantascienza', 'Stati Uniti', 7);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (15, 'Ritratto della giovane in fiamme', 2019, 122, 'Drammatico', 'Francia', 8);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (16, 'Petite maman', 2021, 72, 'Drammatico', 'Francia', 8);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (17, 'Parasite', 2019, 132, 'Thriller', 'Corea del Sud', 9);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (18, 'Memories of Murder', 2003, 131, 'Thriller', 'Corea del Sud', 9);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (19, 'Un affare di famiglia', 2018, 121, 'Drammatico', 'Giappone', 10);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (20, 'Le buone stelle - Broker', 2022, 129, 'Drammatico', 'Corea del Sud', 10);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (21, 'E ora parliamo di Kevin', 2011, 112, 'Drammatico', 'Regno Unito', 11);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (22, 'A Beautiful Day', 2017, 89, 'Thriller', 'Regno Unito', 11);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (23, 'Il profeta', 2009, 155, 'Drammatico', 'Francia', 12);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (24, 'Emilia Perez', 2024, 132, 'Musicale', 'Francia', 12);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (25, 'First Cow', 2019, 122, 'Drammatico', 'Stati Uniti', 13);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (26, 'Showing Up', 2022, 108, 'Commedia', 'Stati Uniti', 13);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (27, '4 mesi, 3 settimane, 2 giorni', 2007, 113, 'Drammatico', 'Romania', 14);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (28, 'R.M.N.', 2022, 125, 'Drammatico', 'Romania', 14);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (29, 'La cienaga', 2001, 103, 'Drammatico', 'Argentina', 15);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (30, 'Zama', 2017, 115, 'Storico', 'Argentina', 15);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (31, 'The Square', 2017, 151, 'Commedia', 'Svezia', 16);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (32, 'Triangle of Sadness', 2022, 147, 'Commedia', 'Svezia', 16);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (33, 'In Darkness', 2011, 145, 'Storico', 'Polonia', 17);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (34, 'Green Border', 2023, 152, 'Drammatico', 'Polonia', 17);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (35, 'C''era una volta in Anatolia', 2011, 157, 'Drammatico', 'Turchia', 18);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (36, 'Il regno d''inverno', 2014, 196, 'Drammatico', 'Turchia', 18);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (37, 'Hereditary', 2018, 127, 'Horror', 'Stati Uniti', 19);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (38, 'Midsommar', 2019, 148, 'Horror', 'Stati Uniti', 19);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (39, 'Atlantique', 2019, 105, 'Drammatico', 'Senegal', 20);
insert into movie (id, title, year, duration, genre, production_country, director_id) values (40, 'Dahomey', 2024, 68, 'Documentario', 'Francia', 20);

-- sale
insert into room (id, name, address, capacity) values (1, 'Sala Grande', 'Lungomare Marconi 90, Venezia Lido', 1032);
insert into room (id, name, address, capacity) values (2, 'Sala Darsena', 'Lungomare Marconi 80, Venezia Lido', 1409);
insert into room (id, name, address, capacity) values (3, 'Sala Perla', 'Via Candia 15, Venezia Lido', 450);
insert into room (id, name, address, capacity) values (4, 'Sala Volpi', 'Lungomare Marconi 90, Venezia Lido', 144);
insert into room (id, name, address, capacity) values (5, 'Sala Giardino', 'Via Sandro Gallo 2, Venezia Lido', 400);
insert into room (id, name, address, capacity) values (6, 'Sala Astra', 'Via Corfu'' 12, Venezia Lido', 280);
insert into room (id, name, address, capacity) values (7, 'Sala Sinopoli', 'Viale Pietro de Coubertin 30, Roma', 1133);
insert into room (id, name, address, capacity) values (8, 'Sala Petrassi', 'Viale Pietro de Coubertin 30, Roma', 673);
insert into room (id, name, address, capacity) values (9, 'Cinema Massimo - Sala Uno', 'Via Giuseppe Verdi 18, Torino', 459);
insert into room (id, name, address, capacity) values (10, 'Auditorium Piazza Liberta''', 'Piazza della Liberta'' 1, Bergamo', 300);

-- festival
insert into festival (id, name, year, city, start_date, end_date, description) values (1, 'Mostra Internazionale d''Arte Cinematografica', 2026, 'Venezia', '2026-09-02', '2026-09-12', 'La rassegna principale: tutti i film del catalogo, in concorso e fuori concorso.');
insert into festival (id, name, year, city, start_date, end_date, description) values (2, 'Festa del Cinema di Roma', 2025, 'Roma', '2025-10-15', '2025-10-26', 'Anteprime e incontri con gli autori all''Auditorium Parco della Musica.');
insert into festival (id, name, year, city, start_date, end_date, description) values (3, 'Torino Film Festival', 2025, 'Torino', '2025-11-21', '2025-11-29', 'Spazio alle opere prime e al cinema indipendente.');
insert into festival (id, name, year, city, start_date, end_date, description) values (4, 'Bergamo Film Meeting', 2026, 'Bergamo', '2026-03-07', '2026-03-15', 'Retrospettive e cinema d''autore europeo.');

-- film partecipanti (molti-a-molti)
insert into festival_movie (festival_id, movie_id) values (1, 1);
insert into festival_movie (festival_id, movie_id) values (1, 2);
insert into festival_movie (festival_id, movie_id) values (1, 3);
insert into festival_movie (festival_id, movie_id) values (1, 4);
insert into festival_movie (festival_id, movie_id) values (1, 5);
insert into festival_movie (festival_id, movie_id) values (1, 6);
insert into festival_movie (festival_id, movie_id) values (1, 7);
insert into festival_movie (festival_id, movie_id) values (1, 8);
insert into festival_movie (festival_id, movie_id) values (1, 9);
insert into festival_movie (festival_id, movie_id) values (1, 10);
insert into festival_movie (festival_id, movie_id) values (1, 11);
insert into festival_movie (festival_id, movie_id) values (1, 12);
insert into festival_movie (festival_id, movie_id) values (1, 13);
insert into festival_movie (festival_id, movie_id) values (1, 14);
insert into festival_movie (festival_id, movie_id) values (1, 15);
insert into festival_movie (festival_id, movie_id) values (1, 16);
insert into festival_movie (festival_id, movie_id) values (1, 17);
insert into festival_movie (festival_id, movie_id) values (1, 18);
insert into festival_movie (festival_id, movie_id) values (1, 19);
insert into festival_movie (festival_id, movie_id) values (1, 20);
insert into festival_movie (festival_id, movie_id) values (1, 21);
insert into festival_movie (festival_id, movie_id) values (1, 22);
insert into festival_movie (festival_id, movie_id) values (1, 23);
insert into festival_movie (festival_id, movie_id) values (1, 24);
insert into festival_movie (festival_id, movie_id) values (1, 25);
insert into festival_movie (festival_id, movie_id) values (1, 26);
insert into festival_movie (festival_id, movie_id) values (1, 27);
insert into festival_movie (festival_id, movie_id) values (1, 28);
insert into festival_movie (festival_id, movie_id) values (1, 29);
insert into festival_movie (festival_id, movie_id) values (1, 30);
insert into festival_movie (festival_id, movie_id) values (1, 31);
insert into festival_movie (festival_id, movie_id) values (1, 32);
insert into festival_movie (festival_id, movie_id) values (1, 33);
insert into festival_movie (festival_id, movie_id) values (1, 34);
insert into festival_movie (festival_id, movie_id) values (1, 35);
insert into festival_movie (festival_id, movie_id) values (1, 36);
insert into festival_movie (festival_id, movie_id) values (1, 37);
insert into festival_movie (festival_id, movie_id) values (1, 38);
insert into festival_movie (festival_id, movie_id) values (1, 39);
insert into festival_movie (festival_id, movie_id) values (1, 40);
insert into festival_movie (festival_id, movie_id) values (2, 1);
insert into festival_movie (festival_id, movie_id) values (2, 3);
insert into festival_movie (festival_id, movie_id) values (2, 5);
insert into festival_movie (festival_id, movie_id) values (2, 7);
insert into festival_movie (festival_id, movie_id) values (2, 9);
insert into festival_movie (festival_id, movie_id) values (2, 11);
insert into festival_movie (festival_id, movie_id) values (2, 13);
insert into festival_movie (festival_id, movie_id) values (2, 15);
insert into festival_movie (festival_id, movie_id) values (2, 17);
insert into festival_movie (festival_id, movie_id) values (2, 19);
insert into festival_movie (festival_id, movie_id) values (2, 21);
insert into festival_movie (festival_id, movie_id) values (2, 23);
insert into festival_movie (festival_id, movie_id) values (2, 25);
insert into festival_movie (festival_id, movie_id) values (2, 27);
insert into festival_movie (festival_id, movie_id) values (2, 29);
insert into festival_movie (festival_id, movie_id) values (3, 2);
insert into festival_movie (festival_id, movie_id) values (3, 4);
insert into festival_movie (festival_id, movie_id) values (3, 6);
insert into festival_movie (festival_id, movie_id) values (3, 8);
insert into festival_movie (festival_id, movie_id) values (3, 10);
insert into festival_movie (festival_id, movie_id) values (3, 12);
insert into festival_movie (festival_id, movie_id) values (3, 14);
insert into festival_movie (festival_id, movie_id) values (3, 16);
insert into festival_movie (festival_id, movie_id) values (3, 18);
insert into festival_movie (festival_id, movie_id) values (3, 20);
insert into festival_movie (festival_id, movie_id) values (3, 22);
insert into festival_movie (festival_id, movie_id) values (3, 24);
insert into festival_movie (festival_id, movie_id) values (4, 15);
insert into festival_movie (festival_id, movie_id) values (4, 16);
insert into festival_movie (festival_id, movie_id) values (4, 29);
insert into festival_movie (festival_id, movie_id) values (4, 30);
insert into festival_movie (festival_id, movie_id) values (4, 35);
insert into festival_movie (festival_id, movie_id) values (4, 36);
insert into festival_movie (festival_id, movie_id) values (4, 39);
insert into festival_movie (festival_id, movie_id) values (4, 40);
insert into festival_movie (festival_id, movie_id) values (4, 31);
insert into festival_movie (festival_id, movie_id) values (4, 32);

-- proiezioni
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (1, '2026-09-02', '10:00', 'SCHEDULED', 1, 1, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (2, '2026-09-02', '15:00', 'SCHEDULED', 1, 2, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (3, '2026-09-02', '20:30', 'SCHEDULED', 1, 3, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (4, '2026-09-02', '10:00', 'SCHEDULED', 1, 4, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (5, '2026-09-02', '15:00', 'SCHEDULED', 1, 5, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (6, '2026-09-02', '20:30', 'SCHEDULED', 1, 6, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (7, '2026-09-02', '10:00', 'SCHEDULED', 1, 7, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (8, '2026-09-02', '15:00', 'SCHEDULED', 1, 8, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (9, '2026-09-02', '20:30', 'SCHEDULED', 1, 9, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (10, '2026-09-02', '10:00', 'SCHEDULED', 1, 10, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (11, '2026-09-02', '15:00', 'SCHEDULED', 1, 11, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (12, '2026-09-02', '20:30', 'SCHEDULED', 1, 12, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (13, '2026-09-02', '10:00', 'SCHEDULED', 1, 13, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (14, '2026-09-02', '15:00', 'SCHEDULED', 1, 14, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (15, '2026-09-02', '20:30', 'SCHEDULED', 1, 15, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (16, '2026-09-02', '10:00', 'SCHEDULED', 1, 16, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (17, '2026-09-02', '15:00', 'CANCELLED', 1, 17, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (18, '2026-09-02', '20:30', 'SCHEDULED', 1, 18, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (19, '2026-09-03', '10:00', 'SCHEDULED', 1, 19, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (20, '2026-09-03', '15:00', 'SCHEDULED', 1, 20, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (21, '2026-09-03', '20:30', 'SCHEDULED', 1, 21, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (22, '2026-09-03', '10:00', 'SCHEDULED', 1, 22, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (23, '2026-09-03', '15:00', 'SCHEDULED', 1, 23, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (24, '2026-09-03', '20:30', 'SCHEDULED', 1, 24, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (25, '2026-09-03', '10:00', 'SCHEDULED', 1, 25, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (26, '2026-09-03', '15:00', 'SCHEDULED', 1, 26, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (27, '2026-09-03', '20:30', 'SCHEDULED', 1, 27, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (28, '2026-09-03', '10:00', 'SCHEDULED', 1, 28, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (29, '2026-09-03', '15:00', 'SCHEDULED', 1, 29, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (30, '2026-09-03', '20:30', 'SCHEDULED', 1, 30, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (31, '2026-09-03', '10:00', 'SCHEDULED', 1, 31, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (32, '2026-09-03', '15:00', 'SCHEDULED', 1, 32, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (33, '2026-09-03', '20:30', 'SCHEDULED', 1, 33, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (34, '2026-09-03', '10:00', 'CANCELLED', 1, 34, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (35, '2026-09-03', '15:00', 'SCHEDULED', 1, 35, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (36, '2026-09-03', '20:30', 'SCHEDULED', 1, 36, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (37, '2026-09-04', '10:00', 'SCHEDULED', 1, 37, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (38, '2026-09-04', '15:00', 'SCHEDULED', 1, 38, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (39, '2026-09-04', '20:30', 'SCHEDULED', 1, 39, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (40, '2026-09-04', '10:00', 'SCHEDULED', 1, 40, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (41, '2026-09-04', '15:00', 'SCHEDULED', 1, 1, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (42, '2026-09-04', '20:30', 'SCHEDULED', 1, 2, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (43, '2026-09-04', '10:00', 'SCHEDULED', 1, 3, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (44, '2026-09-04', '15:00', 'SCHEDULED', 1, 4, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (45, '2026-09-04', '20:30', 'SCHEDULED', 1, 5, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (46, '2026-09-04', '10:00', 'SCHEDULED', 1, 6, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (47, '2026-09-04', '15:00', 'SCHEDULED', 1, 7, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (48, '2026-09-04', '20:30', 'SCHEDULED', 1, 8, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (49, '2026-09-04', '10:00', 'SCHEDULED', 1, 9, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (50, '2026-09-04', '15:00', 'SCHEDULED', 1, 10, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (51, '2026-09-04', '20:30', 'CANCELLED', 1, 11, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (52, '2026-09-04', '10:00', 'SCHEDULED', 1, 12, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (53, '2026-09-04', '15:00', 'SCHEDULED', 1, 13, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (54, '2026-09-04', '20:30', 'SCHEDULED', 1, 14, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (55, '2026-09-05', '10:00', 'SCHEDULED', 1, 15, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (56, '2026-09-05', '15:00', 'SCHEDULED', 1, 16, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (57, '2026-09-05', '20:30', 'SCHEDULED', 1, 17, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (58, '2026-09-05', '10:00', 'SCHEDULED', 1, 18, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (59, '2026-09-05', '15:00', 'SCHEDULED', 1, 19, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (60, '2026-09-05', '20:30', 'SCHEDULED', 1, 20, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (61, '2026-09-05', '10:00', 'SCHEDULED', 1, 21, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (62, '2026-09-05', '15:00', 'SCHEDULED', 1, 22, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (63, '2026-09-05', '20:30', 'SCHEDULED', 1, 23, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (64, '2026-09-05', '10:00', 'SCHEDULED', 1, 24, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (65, '2026-09-05', '15:00', 'SCHEDULED', 1, 25, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (66, '2026-09-05', '20:30', 'SCHEDULED', 1, 26, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (67, '2026-09-05', '10:00', 'SCHEDULED', 1, 27, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (68, '2026-09-05', '15:00', 'CANCELLED', 1, 28, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (69, '2026-09-05', '20:30', 'SCHEDULED', 1, 29, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (70, '2026-09-05', '10:00', 'SCHEDULED', 1, 30, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (71, '2026-09-05', '15:00', 'SCHEDULED', 1, 31, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (72, '2026-09-05', '20:30', 'SCHEDULED', 1, 32, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (73, '2026-09-06', '10:00', 'SCHEDULED', 1, 33, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (74, '2026-09-06', '15:00', 'SCHEDULED', 1, 34, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (75, '2026-09-06', '20:30', 'SCHEDULED', 1, 35, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (76, '2026-09-06', '10:00', 'SCHEDULED', 1, 36, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (77, '2026-09-06', '15:00', 'SCHEDULED', 1, 37, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (78, '2026-09-06', '20:30', 'SCHEDULED', 1, 38, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (79, '2026-09-06', '10:00', 'SCHEDULED', 1, 39, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (80, '2026-09-06', '15:00', 'SCHEDULED', 1, 40, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (81, '2026-09-06', '20:30', 'SCHEDULED', 1, 1, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (82, '2026-09-06', '10:00', 'SCHEDULED', 1, 2, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (83, '2026-09-06', '15:00', 'SCHEDULED', 1, 3, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (84, '2026-09-06', '20:30', 'SCHEDULED', 1, 4, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (85, '2026-09-06', '10:00', 'CANCELLED', 1, 5, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (86, '2026-09-06', '15:00', 'SCHEDULED', 1, 6, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (87, '2026-09-06', '20:30', 'SCHEDULED', 1, 7, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (88, '2026-09-06', '10:00', 'SCHEDULED', 1, 8, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (89, '2026-09-06', '15:00', 'SCHEDULED', 1, 9, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (90, '2026-09-06', '20:30', 'SCHEDULED', 1, 10, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (91, '2026-09-07', '10:00', 'SCHEDULED', 1, 11, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (92, '2026-09-07', '15:00', 'SCHEDULED', 1, 12, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (93, '2026-09-07', '20:30', 'SCHEDULED', 1, 13, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (94, '2026-09-07', '10:00', 'SCHEDULED', 1, 14, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (95, '2026-09-07', '15:00', 'SCHEDULED', 1, 15, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (96, '2026-09-07', '20:30', 'SCHEDULED', 1, 16, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (97, '2026-09-07', '10:00', 'SCHEDULED', 1, 17, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (98, '2026-09-07', '15:00', 'SCHEDULED', 1, 18, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (99, '2026-09-07', '20:30', 'SCHEDULED', 1, 19, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (100, '2026-09-07', '10:00', 'SCHEDULED', 1, 20, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (101, '2026-09-07', '15:00', 'SCHEDULED', 1, 21, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (102, '2026-09-07', '20:30', 'CANCELLED', 1, 22, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (103, '2026-09-07', '10:00', 'SCHEDULED', 1, 23, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (104, '2026-09-07', '15:00', 'SCHEDULED', 1, 24, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (105, '2026-09-07', '20:30', 'SCHEDULED', 1, 25, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (106, '2026-09-07', '10:00', 'SCHEDULED', 1, 26, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (107, '2026-09-07', '15:00', 'SCHEDULED', 1, 27, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (108, '2026-09-07', '20:30', 'SCHEDULED', 1, 28, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (109, '2026-09-08', '10:00', 'SCHEDULED', 1, 29, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (110, '2026-09-08', '15:00', 'SCHEDULED', 1, 30, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (111, '2026-09-08', '20:30', 'SCHEDULED', 1, 31, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (112, '2026-09-08', '10:00', 'SCHEDULED', 1, 32, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (113, '2026-09-08', '15:00', 'SCHEDULED', 1, 33, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (114, '2026-09-08', '20:30', 'SCHEDULED', 1, 34, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (115, '2026-09-08', '10:00', 'SCHEDULED', 1, 35, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (116, '2026-09-08', '15:00', 'SCHEDULED', 1, 36, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (117, '2026-09-08', '20:30', 'SCHEDULED', 1, 37, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (118, '2026-09-08', '10:00', 'SCHEDULED', 1, 38, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (119, '2026-09-08', '15:00', 'CANCELLED', 1, 39, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (120, '2026-09-08', '20:30', 'SCHEDULED', 1, 40, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (121, '2026-09-08', '10:00', 'SCHEDULED', 1, 1, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (122, '2026-09-08', '15:00', 'SCHEDULED', 1, 2, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (123, '2026-09-08', '20:30', 'SCHEDULED', 1, 3, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (124, '2026-09-08', '10:00', 'SCHEDULED', 1, 4, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (125, '2026-09-08', '15:00', 'SCHEDULED', 1, 5, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (126, '2026-09-08', '20:30', 'SCHEDULED', 1, 6, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (127, '2026-09-09', '10:00', 'SCHEDULED', 1, 7, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (128, '2026-09-09', '15:00', 'SCHEDULED', 1, 8, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (129, '2026-09-09', '20:30', 'SCHEDULED', 1, 9, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (130, '2026-09-09', '10:00', 'SCHEDULED', 1, 10, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (131, '2026-09-09', '15:00', 'SCHEDULED', 1, 11, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (132, '2026-09-09', '20:30', 'SCHEDULED', 1, 12, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (133, '2026-09-09', '10:00', 'SCHEDULED', 1, 13, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (134, '2026-09-09', '15:00', 'SCHEDULED', 1, 14, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (135, '2026-09-09', '20:30', 'SCHEDULED', 1, 15, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (136, '2026-09-09', '10:00', 'CANCELLED', 1, 16, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (137, '2026-09-09', '15:00', 'SCHEDULED', 1, 17, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (138, '2026-09-09', '20:30', 'SCHEDULED', 1, 18, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (139, '2026-09-09', '10:00', 'SCHEDULED', 1, 19, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (140, '2026-09-09', '15:00', 'SCHEDULED', 1, 20, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (141, '2026-09-09', '20:30', 'SCHEDULED', 1, 21, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (142, '2026-09-09', '10:00', 'SCHEDULED', 1, 22, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (143, '2026-09-09', '15:00', 'SCHEDULED', 1, 23, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (144, '2026-09-09', '20:30', 'SCHEDULED', 1, 24, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (145, '2026-09-10', '10:00', 'SCHEDULED', 1, 25, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (146, '2026-09-10', '15:00', 'SCHEDULED', 1, 26, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (147, '2026-09-10', '20:30', 'SCHEDULED', 1, 27, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (148, '2026-09-10', '10:00', 'SCHEDULED', 1, 28, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (149, '2026-09-10', '15:00', 'SCHEDULED', 1, 29, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (150, '2026-09-10', '20:30', 'SCHEDULED', 1, 30, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (151, '2026-09-10', '10:00', 'SCHEDULED', 1, 31, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (152, '2026-09-10', '15:00', 'SCHEDULED', 1, 32, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (153, '2026-09-10', '20:30', 'CANCELLED', 1, 33, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (154, '2026-09-10', '10:00', 'SCHEDULED', 1, 34, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (155, '2026-09-10', '15:00', 'SCHEDULED', 1, 35, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (156, '2026-09-10', '20:30', 'SCHEDULED', 1, 36, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (157, '2026-09-10', '10:00', 'SCHEDULED', 1, 37, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (158, '2026-09-10', '15:00', 'SCHEDULED', 1, 38, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (159, '2026-09-10', '20:30', 'SCHEDULED', 1, 39, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (160, '2026-09-10', '10:00', 'SCHEDULED', 1, 40, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (161, '2026-09-10', '15:00', 'SCHEDULED', 1, 1, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (162, '2026-09-10', '20:30', 'SCHEDULED', 1, 2, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (163, '2026-09-11', '10:00', 'SCHEDULED', 1, 3, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (164, '2026-09-11', '15:00', 'SCHEDULED', 1, 4, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (165, '2026-09-11', '20:30', 'SCHEDULED', 1, 5, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (166, '2026-09-11', '10:00', 'SCHEDULED', 1, 6, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (167, '2026-09-11', '15:00', 'SCHEDULED', 1, 7, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (168, '2026-09-11', '20:30', 'SCHEDULED', 1, 8, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (169, '2026-09-11', '10:00', 'SCHEDULED', 1, 9, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (170, '2026-09-11', '15:00', 'CANCELLED', 1, 10, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (171, '2026-09-11', '20:30', 'SCHEDULED', 1, 11, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (172, '2026-09-11', '10:00', 'SCHEDULED', 1, 12, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (173, '2026-09-11', '15:00', 'SCHEDULED', 1, 13, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (174, '2026-09-11', '20:30', 'SCHEDULED', 1, 14, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (175, '2026-09-11', '10:00', 'SCHEDULED', 1, 15, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (176, '2026-09-11', '15:00', 'SCHEDULED', 1, 16, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (177, '2026-09-11', '20:30', 'SCHEDULED', 1, 17, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (178, '2026-09-11', '10:00', 'SCHEDULED', 1, 18, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (179, '2026-09-11', '15:00', 'SCHEDULED', 1, 19, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (180, '2026-09-11', '20:30', 'SCHEDULED', 1, 20, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (181, '2026-09-12', '10:00', 'SCHEDULED', 1, 21, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (182, '2026-09-12', '15:00', 'SCHEDULED', 1, 22, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (183, '2026-09-12', '20:30', 'SCHEDULED', 1, 23, 1);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (184, '2026-09-12', '10:00', 'SCHEDULED', 1, 24, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (185, '2026-09-12', '15:00', 'SCHEDULED', 1, 25, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (186, '2026-09-12', '20:30', 'SCHEDULED', 1, 26, 2);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (187, '2026-09-12', '10:00', 'CANCELLED', 1, 27, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (188, '2026-09-12', '15:00', 'SCHEDULED', 1, 28, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (189, '2026-09-12', '20:30', 'SCHEDULED', 1, 29, 3);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (190, '2026-09-12', '10:00', 'SCHEDULED', 1, 30, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (191, '2026-09-12', '15:00', 'SCHEDULED', 1, 31, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (192, '2026-09-12', '20:30', 'SCHEDULED', 1, 32, 4);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (193, '2026-09-12', '10:00', 'SCHEDULED', 1, 33, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (194, '2026-09-12', '15:00', 'SCHEDULED', 1, 34, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (195, '2026-09-12', '20:30', 'SCHEDULED', 1, 35, 5);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (196, '2026-09-12', '10:00', 'SCHEDULED', 1, 36, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (197, '2026-09-12', '15:00', 'SCHEDULED', 1, 37, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (198, '2026-09-12', '20:30', 'SCHEDULED', 1, 38, 6);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (199, '2025-10-15', '17:00', 'SCHEDULED', 2, 1, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (200, '2025-10-15', '21:00', 'SCHEDULED', 2, 3, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (201, '2025-10-15', '17:00', 'SCHEDULED', 2, 5, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (202, '2025-10-15', '21:00', 'SCHEDULED', 2, 7, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (203, '2025-10-16', '17:00', 'SCHEDULED', 2, 9, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (204, '2025-10-16', '21:00', 'CANCELLED', 2, 11, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (205, '2025-10-16', '17:00', 'SCHEDULED', 2, 13, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (206, '2025-10-16', '21:00', 'SCHEDULED', 2, 15, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (207, '2025-10-17', '17:00', 'SCHEDULED', 2, 17, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (208, '2025-10-17', '21:00', 'SCHEDULED', 2, 19, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (209, '2025-10-17', '17:00', 'SCHEDULED', 2, 21, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (210, '2025-10-17', '21:00', 'SCHEDULED', 2, 23, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (211, '2025-10-18', '17:00', 'SCHEDULED', 2, 25, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (212, '2025-10-18', '21:00', 'SCHEDULED', 2, 27, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (213, '2025-10-18', '17:00', 'SCHEDULED', 2, 29, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (214, '2025-10-18', '21:00', 'SCHEDULED', 2, 1, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (215, '2025-10-19', '17:00', 'SCHEDULED', 2, 3, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (216, '2025-10-19', '21:00', 'SCHEDULED', 2, 5, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (217, '2025-10-19', '17:00', 'SCHEDULED', 2, 7, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (218, '2025-10-19', '21:00', 'SCHEDULED', 2, 9, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (219, '2025-10-20', '17:00', 'SCHEDULED', 2, 11, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (220, '2025-10-20', '21:00', 'SCHEDULED', 2, 13, 7);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (221, '2025-10-20', '17:00', 'CANCELLED', 2, 15, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (222, '2025-10-20', '21:00', 'SCHEDULED', 2, 17, 8);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (223, '2025-11-21', '15:00', 'SCHEDULED', 3, 2, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (224, '2025-11-21', '18:00', 'SCHEDULED', 3, 4, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (225, '2025-11-21', '21:00', 'SCHEDULED', 3, 6, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (226, '2025-11-22', '15:00', 'SCHEDULED', 3, 8, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (227, '2025-11-22', '18:00', 'SCHEDULED', 3, 10, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (228, '2025-11-22', '21:00', 'SCHEDULED', 3, 12, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (229, '2025-11-23', '15:00', 'SCHEDULED', 3, 14, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (230, '2025-11-23', '18:00', 'SCHEDULED', 3, 16, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (231, '2025-11-23', '21:00', 'SCHEDULED', 3, 18, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (232, '2025-11-24', '15:00', 'SCHEDULED', 3, 20, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (233, '2025-11-24', '18:00', 'SCHEDULED', 3, 22, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (234, '2025-11-24', '21:00', 'SCHEDULED', 3, 24, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (235, '2025-11-25', '15:00', 'SCHEDULED', 3, 2, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (236, '2025-11-25', '18:00', 'SCHEDULED', 3, 4, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (237, '2025-11-25', '21:00', 'SCHEDULED', 3, 6, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (238, '2025-11-26', '15:00', 'CANCELLED', 3, 8, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (239, '2025-11-26', '18:00', 'SCHEDULED', 3, 10, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (240, '2025-11-26', '21:00', 'SCHEDULED', 3, 12, 9);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (241, '2026-03-07', '17:00', 'SCHEDULED', 4, 15, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (242, '2026-03-07', '21:00', 'SCHEDULED', 4, 16, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (243, '2026-03-08', '17:00', 'SCHEDULED', 4, 29, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (244, '2026-03-08', '21:00', 'SCHEDULED', 4, 30, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (245, '2026-03-09', '17:00', 'SCHEDULED', 4, 35, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (246, '2026-03-09', '21:00', 'SCHEDULED', 4, 36, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (247, '2026-03-10', '17:00', 'SCHEDULED', 4, 39, 10);
insert into screening (id, screening_date, screening_time, status, festival_id, movie_id, room_id) values (248, '2026-03-10', '21:00', 'SCHEDULED', 4, 40, 10);

-- utenti e credenziali (password: admin -> admin123, altri -> password)
insert into users (id, name, surname, email) values (1, 'Admin', 'Sistema', 'admin@siwfestival.it');
insert into users (id, name, surname, email) values (2, 'Mario', 'Rossi', 'mario.rossi@example.com');
insert into users (id, name, surname, email) values (3, 'Giulia', 'Bianchi', 'giulia.bianchi@example.com');
insert into users (id, name, surname, email) values (4, 'Luca', 'Verdi', 'luca.verdi@example.com');
insert into users (id, name, surname, email) values (5, 'Sara', 'Neri', 'sara.neri@example.com');
insert into credentials (id, username, password, role, user_id) values (1, 'admin', '$2a$10$WiLoDgXmJ5b5DuWBAszAM.nPf.qac.N2RKTbsEpDTZByf/9lqxkXm', 'ADMIN', 1);
insert into credentials (id, username, password, role, user_id) values (2, 'mario', '$2a$10$puFgAJRpowXTEuknFwkN0eV8v7.PEL3o38eqVkU6.iI.5QJ9fgZie', 'USER', 2);
insert into credentials (id, username, password, role, user_id) values (3, 'giulia', '$2a$10$NvUMQikUW5Ul491A.00Pw.9MLTC.4yZ67xp/dIoR1KLCEPPhHINxq', 'USER', 3);
insert into credentials (id, username, password, role, user_id) values (4, 'luca', '$2a$10$ChW7e75StkRrVk8CdHqB.u7.GoHosWmpbKkMf2cmURUwgikxqXWe2', 'USER', 4);
insert into credentials (id, username, password, role, user_id) values (5, 'sara', '$2a$10$bzhBbeBRBS.PAKRxPapulOEYkMgq3sS3MCuO.od62navcVp1qRBdO', 'USER', 5);

-- recensioni (al massimo una per utente e film)
insert into review (id, text, rating, review_date, movie_id, user_id) values (1, 'Il ritmo cala nella parte centrale, ma il finale recupera tutto quello che sembrava perso.', 8, '2026-08-02', 1, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (2, 'Interpretazioni solide e una sceneggiatura che evita ogni facile scorciatoia emotiva.', 9, '2026-08-03', 5, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (3, 'Ambizioso nelle intenzioni, meno riuscito nell''esecuzione. Resta un film che vale la visione.', 10, '2026-08-04', 9, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (4, 'Uno dei lavori piu'' maturi del regista: struttura rigorosa e nessuna concessione al sentimentalismo.', 5, '2026-08-05', 13, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (5, 'La messa in scena e'' notevole, il montaggio meno convincente in alcuni passaggi.', 6, '2026-08-06', 17, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (6, 'Un film che cresce dopo la visione, con immagini che restano addosso per giorni.', 7, '2026-08-07', 21, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (7, 'Convenzionale nella forma ma sincero nel contenuto. Il pubblico in sala ha applaudito.', 8, '2026-08-08', 25, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (8, 'Una regia essenziale che lascia parlare i silenzi. La fotografia sostiene il racconto senza mai sovrastarlo.', 9, '2026-08-09', 29, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (9, 'Il ritmo cala nella parte centrale, ma il finale recupera tutto quello che sembrava perso.', 10, '2026-08-10', 33, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (10, 'Interpretazioni solide e una sceneggiatura che evita ogni facile scorciatoia emotiva.', 5, '2026-08-11', 37, 2);
insert into review (id, text, rating, review_date, movie_id, user_id) values (11, 'Ambizioso nelle intenzioni, meno riuscito nell''esecuzione. Resta un film che vale la visione.', 7, '2026-08-12', 2, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (12, 'Uno dei lavori piu'' maturi del regista: struttura rigorosa e nessuna concessione al sentimentalismo.', 8, '2026-08-13', 6, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (13, 'La messa in scena e'' notevole, il montaggio meno convincente in alcuni passaggi.', 9, '2026-08-14', 10, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (14, 'Un film che cresce dopo la visione, con immagini che restano addosso per giorni.', 10, '2026-08-15', 14, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (15, 'Convenzionale nella forma ma sincero nel contenuto. Il pubblico in sala ha applaudito.', 5, '2026-08-16', 18, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (16, 'Una regia essenziale che lascia parlare i silenzi. La fotografia sostiene il racconto senza mai sovrastarlo.', 6, '2026-08-17', 22, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (17, 'Il ritmo cala nella parte centrale, ma il finale recupera tutto quello che sembrava perso.', 7, '2026-08-18', 26, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (18, 'Interpretazioni solide e una sceneggiatura che evita ogni facile scorciatoia emotiva.', 8, '2026-08-19', 30, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (19, 'Ambizioso nelle intenzioni, meno riuscito nell''esecuzione. Resta un film che vale la visione.', 9, '2026-08-20', 34, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (20, 'Uno dei lavori piu'' maturi del regista: struttura rigorosa e nessuna concessione al sentimentalismo.', 10, '2026-08-21', 38, 3);
insert into review (id, text, rating, review_date, movie_id, user_id) values (21, 'La messa in scena e'' notevole, il montaggio meno convincente in alcuni passaggi.', 6, '2026-08-22', 3, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (22, 'Un film che cresce dopo la visione, con immagini che restano addosso per giorni.', 7, '2026-08-23', 7, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (23, 'Convenzionale nella forma ma sincero nel contenuto. Il pubblico in sala ha applaudito.', 8, '2026-08-24', 11, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (24, 'Una regia essenziale che lascia parlare i silenzi. La fotografia sostiene il racconto senza mai sovrastarlo.', 9, '2026-08-25', 15, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (25, 'Il ritmo cala nella parte centrale, ma il finale recupera tutto quello che sembrava perso.', 10, '2026-08-26', 19, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (26, 'Interpretazioni solide e una sceneggiatura che evita ogni facile scorciatoia emotiva.', 5, '2026-08-27', 23, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (27, 'Ambizioso nelle intenzioni, meno riuscito nell''esecuzione. Resta un film che vale la visione.', 6, '2026-08-28', 27, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (28, 'Uno dei lavori piu'' maturi del regista: struttura rigorosa e nessuna concessione al sentimentalismo.', 7, '2026-08-29', 31, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (29, 'La messa in scena e'' notevole, il montaggio meno convincente in alcuni passaggi.', 8, '2026-08-30', 35, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (30, 'Un film che cresce dopo la visione, con immagini che restano addosso per giorni.', 9, '2026-08-01', 39, 4);
insert into review (id, text, rating, review_date, movie_id, user_id) values (31, 'Convenzionale nella forma ma sincero nel contenuto. Il pubblico in sala ha applaudito.', 5, '2026-08-02', 4, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (32, 'Una regia essenziale che lascia parlare i silenzi. La fotografia sostiene il racconto senza mai sovrastarlo.', 6, '2026-08-03', 8, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (33, 'Il ritmo cala nella parte centrale, ma il finale recupera tutto quello che sembrava perso.', 7, '2026-08-04', 12, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (34, 'Interpretazioni solide e una sceneggiatura che evita ogni facile scorciatoia emotiva.', 8, '2026-08-05', 16, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (35, 'Ambizioso nelle intenzioni, meno riuscito nell''esecuzione. Resta un film che vale la visione.', 9, '2026-08-06', 20, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (36, 'Uno dei lavori piu'' maturi del regista: struttura rigorosa e nessuna concessione al sentimentalismo.', 10, '2026-08-07', 24, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (37, 'La messa in scena e'' notevole, il montaggio meno convincente in alcuni passaggi.', 5, '2026-08-08', 28, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (38, 'Un film che cresce dopo la visione, con immagini che restano addosso per giorni.', 6, '2026-08-09', 32, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (39, 'Convenzionale nella forma ma sincero nel contenuto. Il pubblico in sala ha applaudito.', 7, '2026-08-10', 36, 5);
insert into review (id, text, rating, review_date, movie_id, user_id) values (40, 'Una regia essenziale che lascia parlare i silenzi. La fotografia sostiene il racconto senza mai sovrastarlo.', 8, '2026-08-11', 40, 5);

-- le sequenze usate da Hibernate ripartono da 1000
alter sequence director_seq restart with 1000;
alter sequence movie_seq restart with 1000;
alter sequence room_seq restart with 1000;
alter sequence festival_seq restart with 1000;
alter sequence screening_seq restart with 1000;
alter sequence users_seq restart with 1000;
alter sequence credentials_seq restart with 1000;
alter sequence review_seq restart with 1000;
